### PR TITLE
Reorganized and simplified code, fixed example to work, fixed erroneous javascript example

### LINKED ISSUE #3: some code errors in between, that went unnoticed
Hey Paine,
Hope all is good

the following code is incorrect in the https://github.com/painebenjamin/hey-buddy/blob/main/src/js/src/hey-buddy.js file

```javascript
        // Push the embedding into the buffer
        if (this.embeddingBuffer === null) {
            this.embeddingBuffer = await ONNX.createTensor(
                "float32",
                embedding.data,
                [embedding.dims[embedding.dims.length-2], this.embeddingDim]
            );
        } else {
            const toShift = this.embeddingBuffer.dims[0] + embedding.dims[0] - this.wakeWordEmbeddingFrames;
            // Shift back
            if (toShift > 0) {
                if (this.embeddingBuffer.dims[0] < this.wakeWordEmbeddingFrames) {
                    const embeddingData = new Float32Array(this.wakeWordEmbeddingFrames * this.embeddingDim);
                    embeddingData.set(this.embeddingBuffer.data.subarray(toShift * this.embeddingDim));
                    embeddingData.set(embedding.data, this.wakeWordEmbeddingFrames - embedding.dims[0]);
                    this.embeddingBuffer = await ONNX.createTensor(
                        "float32",
                        embeddingData,
                        [this.wakeWordEmbeddingFrames, this.embeddingDim]
                    );
                } else {
                    this.embeddingBuffer.data.set(this.embeddingBuffer.data.subarray(toShift * this.embeddingDim));
                    this.embeddingBuffer.data.set(embedding.data, this.embeddingBuffer.length - this.embeddingDim);
                }
            } else {
                // Append
                const embeddingData = new Float32Array(this.embeddingBuffer.data.length + embedding.data.length);
                embeddingData.set(this.embeddingBuffer.data);
                embeddingData.set(embedding.data, this.embeddingBuffer.data.length);
                this.embeddingBuffer = await ONNX.createTensor(
                    "float32",
                    embeddingData,
                    [this.embeddingBuffer.dims[0] + embedding.dims[0], this.embeddingDim]
                );
            }
 ```

it is incorrect for 2 reasons

(1), this.embeddingBuffer.dims[0] < this.wakeWordEmbeddingFrames will never be true, as if it were, then toShift would have to be negative, my understanding is that this.embeddingBuffer.dims[0] gives the current number of frames

(2) this.embeddingBuffer.length is undefined, since embeddingBuffer is a ONNX tensor, i think you need to do something with  embeddingBuffer.dims here

I'll send a PR if I get a chance

### LINKED ISSUE #4: Hey Paine!, Just would like to know if this codebase is maintained
Hey Paine!
I am working on some optimizations to make the js code compatible with node, and also to migrate the code to typescript – Would love to know if you plan on maintaining the code (in which case I'll send a PR here) – or you would prefer I do these things seperately in a different repository

Thanks in advance!

### PR DESCRIPTION
**Pull request by therealadityashankar**
This pull-request makes the following changes

- It fixes the index.html file to have onnx and index.js to have the root url (closes #3 )
- It reorganizes the hey-buddy.js code to it's principal components (as to simplify the code) (closes #4 ), so that users need not think about tensors for the most part, while using the code base
- Adds venv to gitignore since it creates alot of not-needed to be committed files

Let me know if the commit is too big or if you would prefer the files be split apart

### CODE REVIEW

File: src/js/src/hey-buddy.js [hunk 1]
```diff
@@ -8,6 +8,25 @@ import {
     WakeWord
 } from "./models.js";
 
+async function embeddingBufferArrayToEmbedding(embeddingBufferArray, numFramesPerEmbedding, embeddingDim){
```
Comment (painebenjamin) [inline src/js/src/hey-buddy.js:11]: Could you add a brief docblock to this method, similar to the other ones?

File: src/js/src/hey-buddy.js [hunk 2]
```diff
@@ -8,6 +8,25 @@ import {
...
+        combinedEmptyData,
+        [numFramesPerEmbedding * embeddingBufferArray.length, embeddingDim]
+    );
+
+    // Fill the buffer with data
+    for (let i = 0; i < embeddingBufferArray.length; i++) {
+        const embedding = embeddingBufferArray[i];
+        embeddingBuffer.data.set(embedding.data, i * numFramesPerEmbedding * embeddingDim);
+    }
+    return embeddingBuffer
```
Comment (painebenjamin) [inline src/js/src/hey-buddy.js:27]: Let's keep all JS lines ending with a semicolon for the sake of consistency.

File: src/js/src/hey-buddy.js [hunk 3]
```diff
@@ -305,103 +321,39 @@ export class HeyBuddy {
...
-                this.listening = false;
-            }
-        } else {
-            this.negatives = 0;
-            if (!this.listening) {
-                this.speechStart();
-            }
-            this.listening = true;
-        }
+        this.embeddingBufferArray.push(embedding)
```
Comment (painebenjamin) [inline src/js/src/hey-buddy.js:330]: Semicolon

File: src/js/src/hey-buddy.js [hunk 4]
```diff
@@ -305,103 +321,39 @@ export class HeyBuddy {
...
-                embeddingData.set(embedding.data, this.embeddingBuffer.data.length);
-                this.embeddingBuffer = await ONNX.createTensor(
-                    "float32",
-                    embeddingData,
-                    [this.embeddingBuffer.dims[0] + embedding.dims[0], this.embeddingDim]
-                );
-            }
-        }
+        const embedding = await this.embedding.getEmbeddingFromMelSpectrogramOutput(spectrograms);
+        const numFramesPerEmbedding = embedding.dims[0]
```
Comment (painebenjamin) [inline src/js/src/hey-buddy.js:327]: Semicolon

File: src/js/src/hey-buddy.js [hunk 5]
```diff
@@ -305,103 +321,39 @@ export class HeyBuddy {
...
-        } else {
-            this.negatives = 0;
-            if (!this.listening) {
-                this.speechStart();
-            }
-            this.listening = true;
-        }
+        this.embeddingBufferArray.push(embedding)
+
+        if (this.embeddingBufferArray.length > maxEmbeddings) this.embeddingBufferArray.shift()
```
Comment (painebenjamin) [inline src/js/src/hey-buddy.js:332]: Semicolon

File: src/js/src/hey-buddy.js [hunk 6]
```diff
@@ -305,103 +321,39 @@ export class HeyBuddy {
...
+
+        this.embeddingBuffer = await embeddingBufferArrayToEmbedding(this.embeddingBufferArray, numFramesPerEmbedding, this.embeddingDim)
```
Comment (painebenjamin) [inline src/js/src/hey-buddy.js:334]: Semicolon

File: src/js/src/models/wake-word.js [hunk 7]
```diff
@@ -48,4 +66,30 @@ export class WakeWord extends ONNXModel {
...
+
+    /**
+     * Check if the wake word is detected based on the threshold
+     * @param {Float32Array} embeddings - Input embeddings
+     * @returns {Promise<Object>} - Promise that resolves with an object containing probability and detected status
+     */
+    async checkWakeWordCalled(embeddings) {
+        const probability = await this.run(embeddings);
+
+        if (probability > this.threshold) {
```
Comment (painebenjamin) [inline src/js/src/models/wake-word.js:78]: Let's just remove this section, we'll keep debugging messages out of the main branch.

**Review by painebenjamin — CHANGES_REQUESTED** [review]
Thank you for this, it looks fantastic! I just had a couple style-related comments I'd love if you took a look at, then we can get this merged. :smile:

File: src/js/src/models/wake-word.js (hunk 7 above)
Comment (therealadityashankar) [reply src/js/src/models/wake-word.js:78]: Hey thanks for the rest of the recommendations!, appreciate it alot! -  just part this isn't for debugging – I moved the logic for checking if wake words are called into src/js/src/hey-buddy.js, 

I personally prefer this since it makes it more obvious to the reader what that code does as opposed to .run(), but if you still feel like this is unnecessary – I'd be happy to rewrite both files!

Comment (painebenjamin) [reply src/js/src/models/wake-word.js:78]: Sorry if I was unclear - I was only referring to this particular `if` statement and the `console.log` within it, not the whole `checkWakeWordCalled` method.

**Review by painebenjamin — APPROVED** [review]
